spring:
  application:
    name: config_server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/larionovda/app-config.git

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: true

server:
  port: ${CONFIG_PORT:8888}