endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: true

spring:
  application:
    name: sample-api-gateway

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: true

zuul:
  routes:
    workspaces-service:
       serviceId: workspaces-api
    employees-service:
      serviceId: employees-api